
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # setup dotnet
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
  
    #build
    - name: Build
      run: |
        dotnet --info
        dotnet build